// This file is generated by yarn build_catalogue. Run it again when solutions are added or removed.
import { type Solution } from "@/lib/common/domain/values/Solution";
import { solution as solution01 } from "./01";
import { solution as solution02 } from "./02";
import { solution as solution03 } from "./03";
import { solution as solution04 } from "./04";
import { solution as solution05 } from "./05";
import { solution as solution06 } from "./06";
import { solution as solution07 } from "./07";
import { solution as solution08 } from "./08";
import { solution as solution10 } from "./10";
import { solution as solution11 } from "./11";
import { solution as solution12 } from "./12";
import { solution as solution13 } from "./13";
import { solution as solution15 } from "./15";
import { solution as solution16 } from "./16";
import { solution as solution20 } from "./20";
import { solution as solution21 } from "./21";
import { solution as solution22 } from "./22";
import { solution as solution23 } from "./23";
import { solution as solution25 } from "./25";
import { solution as solution26 } from "./26";
import { solution as solution30 } from "./30";
import { solution as solution31 } from "./31";
import { solution as solution32 } from "./32";
import { solution as solution40 } from "./40";
import { solution as solution50 } from "./50";
import { solution as solution51 } from "./51";
import { solution as solution52 } from "./52";
import { solution as solution53 } from "./53";
import { solution as solution54 } from "./54";
import { solution as solution60 } from "./60";
import { solution as solution61 } from "./61";

export const catalogueSolutions = {
  "01": solution01,
  "02": solution02,
  "03": solution03,
  "04": solution04,
  "05": solution05,
  "06": solution06,
  "07": solution07,
  "08": solution08,
  "10": solution10,
  "11": solution11,
  "12": solution12,
  "13": solution13,
  "15": solution15,
  "16": solution16,
  "20": solution20,
  "21": solution21,
  "22": solution22,
  "23": solution23,
  "25": solution25,
  "26": solution26,
  "30": solution30,
  "31": solution31,
  "32": solution32,
  "40": solution40,
  "50": solution50,
  "51": solution51,
  "52": solution52,
  "53": solution53,
  "54": solution54,
  "60": solution60,
  "61": solution61,
} as Record<string, Solution>;
