name: Build

on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  build:
    name: Build and export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
      - name: Build and export
        run: |
          yarn build
